import { Project } from "./type";
import i18n, { t } from "i18next";

export const projects: Project[] = [
  {
    id: "1",
    title: "FCC projects",
    body: "Collezione di cinque progetti realizzati per ottenere la certificazione responsive web design di FreeCodeCamp. I progetti sono stati sviluppati in codepen usando principlamente HTML e CSS.",
    bodyEng:
      "A collection of five projects made in order to obtain the FreeCodeCamp responsive web design certification. The projects are developed on codepen, using mainly HTML and CSS.",
    type: ["web design", "frontend"],
    year: "2021",
    tools: ["codepen"],
    img: "/img/projects/fccprojects.png",
    path: "/fcc",
  },
  {
    id: "2",
    title: "Datalab: bicocca data science lab",
    body: "Progetto realizzato in relazione all'elaborato di tesi di laurea magistrale. Si tratta del deisng (dalla fase di analisi, alla creazione del logo, del visual design e dei wireframe fino ad arrivare alla creazione di prototipi e mockup) e dello sviluppo (tramite WordPress) del sito web del laboratorio di data science laboratory dell'Univeristà Milano-Bicocca. Durante il progetto ho anche svolto una fase di user testing e analisi.",
    bodyEng:
      "This project is related to my master’s thesis, and it’s the design (from an analysis pahse to logo and visual design, wireframing, prototyping and mockups phase) and development (via WordPress) of a website for the data science laboratory of the University of Milano-Bicocca. The project also featured user testing and analysis on the website.",
    type: ["web design", "visual design", "UX/UI"],
    year: "2020/2021",
    tools: ["WordPress", "Figma", "Affinity Designer"],
    img: "/img/projects/datalab.jpg",
    best: true,
    path: "/datalab",
  },
  {
    id: "3",
    title: "OBI Service Design",
    body: "Design e prototipo di un'app modbile creata per OBI durante la Reply Creative Challenge 2020, una sfida creativa in team della durata di 48 ore realizzata da Reply.",
    bodyEng:
      "Design and prototype of a mobile app created for OBI during the Reply Creative Challenge 2020, a 48 hours long creative challenge in team hosted by Reply.",
    type: ["app design", "UX/UI"],
    year: "2020",
    tools: ["figma", "InVision"],
    img: "/img/projects/obi.png",
    best: true,
    path: "/obi",
  },
  {
    id: "4",
    title: "Redesign associazione astronomica",
    body: "Redesign e sviluppo del sito web di un'organizzazione non-profit dedicata all'astronimia. Il progetto di gruppo era parte di un corso univeritario e ha compreso anche fasi di analisi e di user research.",
    bodyEng:
      "Redesign and development of a website for a non-profit organization dedicated to astronomy. The team project was part of an university course.",
    type: ["web design", "UX/UI"],
    year: "2019/2020",
    tools: ["Adobe Photoshop", "XD"],
    img: "/img/projects/assastro.png",
    best: true,
    path: "/redesign-assastro",
  },
  {
    id: "5",
    title: "Save the Kouprey",
    body: "Design e sviluppo di un sito web foundraiser per il WWF con l'obiettivo di raccogliere fondi a favore di uno dei tanti animali in via d'estionzione, aka l'elusivo Kouprey.",
    bodyEng:
      "Design and development of a fundraiser website aiming to raise funds for a WWF’s endangered species, aka the elusive Kouprey.",
    type: ["web design", "frontend"],
    year: "2019",
    tools: ["Adobe Photoshop", "Adobe Dreamweaver"],
    img: "/img/projects/kouprey.png",
    best: true,
    path: "/kouprey",
  },
  {
    id: "6",
    title: "FindMe",
    body: "Design e mockup di una piattaforma online con l'obiettivo di aiutare i giovani a trovare il lavoro perfetto, mettendo a disposizione un sistema di matching tra offerta e candidato e un sistema che li aiuti a costruire un cv personalizzato sulla base di diversi fattori.",
    bodyEng:
      "Design and mockup of an online platform that aims to help young people finding the perfect job, providing them with a matching system and a way that helps them with building a personalized cv based on several factors.",
    type: ["web design", "UX/UI"],
    year: "2019",
    tools: ["Adobe Photoshop", "Adobe Illustrator"],
    img: "/img/projects/findme.png",
    best: true,
    path: "/findme",
  },
  {
    id: "7",
    title: "Functional Office Experience",
    body: "Design e prototipo di un sistema context-aware con l'obiettivo di semplificare la user experience delle persone che lavorano in uffici condivisi o spazi di co-working.",
    bodyEng:
      "Design and prototype of a context-aware system that aims to facilitate the user experience of people working in shared offices or co-working spaces.",
    type: ["UX/UI"],
    year: "2019",
    tools: ["Adobe Photoshop", "Adobe XD"],
    img: "/img/projects/fox.png",
    path: "/fox",
  },
  {
    id: "8",
    title: "evolveITup: digital for business",
    body: "Design e sviluppo di un blog WordPress dedicato al tema del digitale e le piccole imprese. Il progetto era parte di un lavoro di gruppo universitario, il nostro team si è inoltre occupato di scrivere e pubblicatare articoli relativi ai temi del blog e di curare gli account social del blog, analizzandone l'andamento.",
    bodyEng:
      "Design and development of a WordPress blog about digital and small businesses. The project was part of a group assignment for an university course, our team also wrote and published articles related to the blog’s theme and we also managed the blog’s social accounts.",
    type: ["web design", "frontend", "social network"],
    year: "2019",
    tools: ["WordPress", "Photoshop", "Illustrator"],
    img: "/img/projects/evolveitup.png",
    best: true,
    path: "/evolveitup",
  },
  {
    id: "9",
    title: "Bookie: il tuo assistente virtuale",
    body: "Design e prototipo di un'app modbile e di un chatbot, il tutto realizzato in un solo giorno durante il BiblioHackDay, un hackaton in team organizzato dall'Università Milano-Bicocca. L'app Bookie ha come obiettivo quello di aiutare gli stuendi e gli utilizzatori della bibloteca universitaria nell'utilizzo dei suoi vari servizi. Il nostro team e la nostra app Bookie si sono aggiudicati il primo premio!",
    bodyEng:
      "Design and prototype of a mobile app and chatbot made in the span of a day during the BiblioHackDay, a team hackaton hosted by the University of Milano-Bicocca. The app aims to help students and users of the university’s library in using its various services. Our team and our bookie app won the first prize!",
    type: ["app design"],
    year: "2019",
    tools: ["Adobe Photoshp", "Adobe Illustrator"],
    img: "/img/projects/bookie.png",
    best: true,
    path: "/bookie",
  },
  {
    id: "10",
    title: "e-Lux: la tua bolletta intelligente",
    body: "Design e mockup di un'app mobile e di un documento dinamico per una bolletta dell'elettricità.",
    bodyEng:
      "Design and mockup of an app and a dynamic document for an electricity bill.",
    type: ["app design"],
    year: "2019",
    tools: ["Adobe Photoshop"],
    img: "/img/projects/elux.png",
    path: "/elux",
  },
  //   {
  //     id: "0",
  //     title: "",
  //     body: "",
  //     type: [""],
  //     year: "",
  //     tools: [""],
  //     img: "",
  //   },
];
